### ISSUE TITLE
Can MESSAGEPARTS_MAXIMUM be set to 10?

### ISSUE THREAD

**Issue by Nizari** [cmdotcom/text-sdk-php#12]
You now have a  `__set ` method in the Message class. But now the phpstan
wil give an error as follows. Either please create a normal set method or set the constant `MESSAGEPARTS_MAXIMUM` to 10 would be very much appreciated.

``` Access to private property CMText\Message::$maximumNumberOfMessageParts. ```

**Comment by hexonthebeach** [comment]
Hi Nizari, from what I can find it looks like phpstan has problems understanding magic methods.
You can solve this by using an extension for phpstan or write a regular expression to ignore errors related to magic methods.

**Comment by Ibocann** [comment]
00316012345678
