### ISSUE TITLE
Missing Guzzle from deprecated sdk

### ISSUE THREAD

**Issue by DannyvdSluijs** [cmdotcom/text-sdk-php#16]
Since this sdk replaces https://github.com/CMTelecom/messaging-php it would be helpful for people to have a more like for like replacement.

In my implementations of the previous sdk I've used the guzzle and its middleware for a different amount of extensions. Two of the most basic ones are logging (using out of the box Guzzle middleware) and testability (replacing the Guzzle handler with a Guzzle mock handler)

Is there any plans to update the curl implementation with Guzzle or are you willing to accept an PR that does just that?

**Comment by joepb** [comment]
Hi Danny,

Sorry for the (very) late reply. 

We have no concrete plans for a Guzzle implementation.
PRs are always welcome, that's for sure.
To be honest I am not well enough introduced into this matter to decide if Guzzle is something we do or do not want. @hexonthebeach can you comment on that?

Thanks,
Joep

**Comment by tvdijen** [comment]
You really do want Guzzle!!
