### ISSUE TITLE
Sender Name Japanese Problem.

### ISSUE THREAD

**Issue by ReallyBean** [cmdotcom/text-sdk-php#19]
I'd like to send the sms with japanese sender name.
But It's marked ??.

What is the solution in this case?

Thanks.

**Comment by hexonthebeach** [comment]
This is a technical limitation of SMS messaging @ReallyBean .
Supported characters in the sendername consist of the ones in the GSM characterset : https://en.wikipedia.org/wiki/GSM_03.38
Using characters from the extended/shifted tables requires correct use of the UDH, which is not in the SDK currently.

Hope this help,
Kind regards
