### ISSUE TITLE
Typos in README.md

### ISSUE THREAD

**Issue by ganboonhong** [cmdotcom/text-sdk-php#29]
https://github.com/cmdotcom/text-sdk-php/blob/4704b76228b8f6020e23b71eb1d63ca8c5468b17/README.md#L89
https://github.com/cmdotcom/text-sdk-php/blob/4704b76228b8f6020e23b71eb1d63ca8c5468b17/README.md#L114

`Channels::WhatsApp` should be `Channels:: WHATSAPP` since the definition is:

https://github.com/cmdotcom/text-sdk-php/blob/4704b76228b8f6020e23b71eb1d63ca8c5468b17/src/CMText/Channels.php#L24

**Comment by hexonthebeach** [comment]
Thanks for mentioning @ganboonhong ! You're absolutely right.

I will change it soon and make sure it is correct in the next release, feel free to send a pr if you think it takes too long.
