### ISSUE TITLE
SendMessage

### ISSUE THREAD

**Issue by pengchangxi** [cmdotcom/text-sdk-php#47]
"statusMessage": "Created 1 message(s)",
        "statusCode": 0,
        "details": [
            {
                "to": "86132xxxxxxxx",
                "status": "Accepted",
                "reference": "4950fb39-bcfd-4ce1-b731-612ab9840e20",
                "parts": 1,
                "messageDetails": null,
                "messageErrorCode": 0
            }
        ]

But I didn't receive the text message

**Comment by hexonthebeach** [comment]
Hi @pengchangxi , you can log in to the CM platform and find your message history, that way you can probably find out what is going on with this message.

Otherwise please contact support for this kind of questions.
https://www.cm.com/nl-nl/contact/support/
