### ISSUE TITLE
Cannot send non-English text message.

### ISSUE THREAD

**Issue by vinsonyung** [cmdotcom/text-sdk-php#7]
`
$client = new TextClient("{{API_KEY}}");
$content = '你好';
$result = $client->SendMessage($content, 'Test', ['00852xxxxxxxx']);
`

Response:
`TextClientResult {#592 ▼
  -httpStatusCode: 200
  -response: """
    {
      "details": "Created 1 message(s)",
      "errorCode": 0,
      "messages": [
        {
          "to": "00852xxxxxxxx",
          "status": "Accepted",
          "reference": null,
          "parts": 1,
          "messageDetails": null,
          "messageErrorCode": 0
        }
      ]
    }
    """
  +statusMessage: "Created 1 message(s)"
  +statusCode: 0
  +details: array:1 [▼
    0 => {#594 ▼
      +"to": "00852xxxxxxxx"
      +"status": "Accepted"
      +"reference": null
      +"parts": 1
      +"messageDetails": null
      +"messageErrorCode": 0
    }
  ]
}`

However, in Message log, it shows the message status is "Cancelled".

**Comment by hexonthebeach** [comment]
Unicode characters should not be a problem @vinsonyung 

You can probably solve this specific incident by getting into contact with our support team.
