### ISSUE TITLE
Is there an SDK For making Whatsapp webhooks

### ISSUE THREAD

**Issue by tmawarire** [cmdotcom/text-sdk-php#9]
Hi guys i need assistance. I have been trying to get to you but to no avail, is there an SDK for creating Whatsapp webhooks. If not, how do I go about doing that in PHP. I am behind time, i hope you assist me. Thank you in advance.

**Comment by hexonthebeach** [comment]
Hi tmawarire, there is no sdk for receiving webhooks currently, you can check out the documentation on webhooks for incoming messages here :
https://docs.cmtelecom.com/en/api/mo-webhooks/1.0/index
